#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Running lint and format checks with Bun..."

# Run lint-staged and format checks
if bun x lint-staged && bun run format:check; then
  echo "✅ Lint and format checks passed!"
  
  echo "📦 Building the project with Bun..."
  if bun run build; then
    echo "✅ Build passed!"
  else
    echo "❌ Build failed. Commit aborted."
    exit 1
  fi

else
  echo "❌ Lint or format checks failed. Commit aborted."
  exit 1
fi
